-- AUDIT LOG
CREATE TABLE AuditLogs (
    Id INT PRIMARY KEY IDENTITY(1,1),
    RowId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    UserId INT NULL,
    TableName VARCHAR(100) NOT NULL,
    RecordId VARCHAR(100) NOT NULL,
    Action VARCHAR(20) NOT NULL,
    OldData VARCHAR(MAX) NULL,
    NewData VARCHAR(MAX) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_AuditLogs_UserId FOREIGN KEY (UserId) REFERENCES Users(Id)
);