-- ROLES
CREATE TABLE Roles (
    [Id]			INT					PRIMARY KEY IDENTITY(1,1),
    [RowId]			UNIQUEIDENTIFIER	NOT NULL DEFAULT NEWID(),
    [Name]			NVARCHAR(50)		NOT NULL UNIQUE,
    [CreatedAt]		DATETIME			NOT NULL DEFAULT GETDATE()
);