-- SYSTEM LOG
CREATE TABLE SystemLogs (
    Id      INT PRIMARY KEY IDENTITY(1,1),
    RowId   UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Level VARCHAR(20) NOT NULL,
    Message VARCHAR(MAX) NOT NULL,
    Context VARCHAR(255) NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);